export const routes = {
  // 首页
  index: "/pages/index/index",
  // 关于页面
  about: "/pages/about/about",
  // 客服页面
  service: "/pages/service/service",
  // 客服页面(无导航栏)
  service2: "/pages/service/service2",
  // 公司官网页面
  website: "/pages/website/website",
  // 登录页面
  login: "/pages/login/index",
  // 注册页面
  register: "/pages/register/index",
  // 邮箱验证码页面
  emailCode: "/pages/register/email_code",
  // 忘记密码页面
  forgotEmail: "/pages/forgot/email",
  // 邮箱重置登录密码页面
  emailResetPass: "/pages/login_pwd/email_reset",
  // 邮箱重置支付密码页面
  emailResetPayPass: "/pages/pay_pwd/email_reset",
  // 个人中心
  profile: "/pages/profile/index",
  // 版本更新页面
  versionUpdate: "/pages/version_update/download",
  // 邀请好友页面
  inviteDetail: "/pages/invite/detail",
  // 应用下载页面
  inviteIndex: "/pages/invite/index",
  // 下载安装常见问题页面
  appDownloadContent: "/pages/invite/content",
  // 忘记密码页面
  forgot: "/pages/forgot/phone",
  // 修改登录密码页面
  editPassword: "/pages/login_pwd/pwd_reset",
  // 验证密钥页面
  verifyMiYao: "/pages/miyao/verification",
  // 使用密钥重置密码页面
  editResetPass: "/pages/login_pwd/miyao_reset",
  // 设置支付密码页面
  payPassNew: "/pages/pay_pwd/pwd_update",
  // 重置支付密码页面
  editPayPass: "/pages/pay_pwd/miyao_reset",
  // 实名认证页面
  certification: "/pages/certification/index",
  // 地址列表页面
  address: "/pages/address/index",
  // 添加地址页面
  addressAdd: "/pages/address/update",
  // 找回密码成功页面
  zhaoHuiSuccess: "/pages/login_pwd/reset_success",
  // 查看密钥页面
  passwordKey: "/pages/miyao/show",
  // 我的密钥页面
  miYao: "/pages/miyao/copy",
  // 会员等级页面
  membershipLevel: "/pages/vip/membership_level",
  // 会员卡购买页面
  vipCardPurchase: "/pages/vip/vip_card_purchase",
  // 会员卡购买记录页面
  vipCardPurchaseRecord: "/pages/vip/vip_card_record",
  // 团队等级页面
  teamLevel: "/pages/vip/team_level",
  // 团队奖励页面
  teamLevelJiangli: "/pages/vip/team_level_record",
  // 应用升级页面
  upApp: "/pages/version_update/index",
  // 投资页面
  invest: "/pages/product/invest",
  // 创投中心页面
  product: "/pages/product/product",
  // 详情列表页面
  productDetailsList: "/pages/product/product_details_list",
  // 产品项目列表页面
  productList: "/pages/product/product_list",
  // 投资详情页面
  productDetail: "/pages/product/product_detail",
  // 团购记录页面
  pinTuanJiLu: "/pages/product/pin_tuan_ji_lu",
  // 拼团详情页面
  pinTuanDetail: "/pages/product/pin_tuan_detail",
  // 拼团投资页面
  pinTuanBuy: "/pages/product/pin_tuan_buy",
  // 投资合同页面
  touZiHeTong: "/pages/other_view/tou_zi_he_tong",
  // 电子签名页面
  dianZiQianMing: "/pages/other_view/dian_zi_qian_ming",
  // 我的投资记录页面
  productJiLu: "/pages/product/product_ji_lu",
  // 贷款页面
  daiKuan: "/pages/dai_kuan/dai_kuan",
  // 贷款记录页面
  daiKuanJiLu: "/pages/dai_kuan/dai_kuan_ji_lu",
  // 贷款合同详情页面
  daiKuanHeTong: "/pages/dai_kuan/dai_kuan_he_tong",
  // 申请还款页面
  daiKuanHuanKuan: "/pages/dai_kuan/dai_kuan_huan_kuan",
  // 贷款合同详情页面
  daiKuanHeTongShow: "/pages/dai_kuan/dai_kuan_he_tong_show",
  // 提前还款页面
  daiKuanTiQian: "/pages/dai_kuan/dai_kuan_ti_qian",
  // 还款记录页面
  huanKuanJiLu: "/pages/dai_kuan/huan_kuan_ji_lu",
  // 在线充值页面
  recharge: "/pages/recharge/index",
  // 充值记录页面
  rechargeRecord: "/pages/recharge/record",
  // 转账页面
  transfer: "/pages/transfer/index",
  // 转账记录页面
  transferRecord: "/pages/transfer/record",
  // 提现页面
  withdraw: "/pages/withdraw/index",
  // 提现记录页面
  withdrawRecord: "/pages/withdraw/record",
  // 提现管理页面
  wallet: "/pages/wallet/index",
  // 编辑提现管理页面
  walletEdit: "/pages/wallet/edit",
  // 余额宝页面
  yuebao: "/pages/yuebao/index",
  // 余额宝转账页面
  yuebaoTransfer: "/pages/yuebao/transfer",
  // 交易明细页面
  flowRecord: "/pages/transaction_detail/index",
  // 推广记录页面
  promoRecord: "/pages/team_record/index",
  // 现金券页面
  cashCoupon: "/pages/coupon/voucher",
  // 加息券页面
  rateCoupon: "/pages/coupon/interest_rate",
  // 转让加息券
  rateTransfer: "/pages/coupon/transfer",
  // 计算器页面
  calc: "/pages/calc/index",
  // 通用文章详情页
  articleInfo: "/pages/about/article_info",
  // 视频播放页面
  videoView: "/pages/about/videoview",
  // 每日签到页面
  checkIn: "/pages/checkin/index",
  // 每日签到记录页面
  checkInRecord: "/pages/checkin/record",
  // 抽奖页面
  lottery: "/pages/lottery/index",
  // 抽奖记录页面
  lotteryRecord: "/pages/lottery/record",
  // 资讯列表页面
  newsList: "/pages/news_list/index",
  // 资讯详情页面
  newsDetail: "/pages/about/new_details",
  // 电子签名页面
  electronicSignature: "/pages/other_view/dian_zi_qian_ming",

  // 账户详情页面
  accountDetails: "/pages/account/detail",
  // 文章详情页面
  articleView: "/pages/about/pageview",
  // 积分商城页面
  storeList: "/pages/store/list",
  // 投资购买页面
  productBuy: "/pages/product/product_buy",
  // 积分兑换记录页面
  exchangeMoneyLogs: "/pages/store/exchange_money_logs",
  // 积分兑换记录页面 二级页面
  exchangeMoneyLogsIndex: "/pages/store/exchange_logs_index",
  // 积分兑换页面
  exchangeMoney: "/pages/store/exchange_money",
  // 积分兑换记录页面
  exchangeLogs: "/pages/store/exchange_logs",
  // 积分兑换盲盒抽奖记录页面
  exchangeLotteryLogs: "/pages/store/exchange_lottery_logs",
  // 积分兑换盲盒抽奖页面
  exchangeLottery: "/pages/store/exchange_lottery",
  // 积分兑换商品详情页面
  exchangeProductDetail: "/pages/store/detail",
  // 商品结算页面
  exchange: "/pages/store/exchange",
  // 学堂页面
  indexGuide: "/pages/guide/index",
  // 钱包类型页面
  walletType: "/pages/wallet/type",
  // 余额宝复利计算器页面
  yuebaoCalc: "/pages/yuebao/calc",
  // 奖励与收益明细页面
  accountRecord: "/pages/account/record",
  // 股权中心相关页面
  equity: "/pages/equity/index",
  // 股权购买页面
  equityPurchase: "/pages/equity/purchase",
  // 股权质押页面
  equityRelease: "/pages/equity/release",
  // 股权合约页面
  equityContract: "/pages/equity/contract",
  // 股权交易页面
  equityTrade: "/pages/equity/trade",
  // 股权记录页面
  equityRecord: "/pages/equity/record",
  // 股权详情页面
  equityDetail: "/pages/product/product_equity_detail",
  // 股权查看合约页面
  equityAgreement: "/pages/equity/agreement",
  // 股权订单页面
  equityOrder: "/pages/equity/order",
  // 股权限价交易页面
  equityLimitOrder: "/pages/equity/limit_order",
  // 股权市价交易页面
  equityMarketOrder: "/pages/equity/market_order",
  // 语言设置页面
  lang: "/pages/lang/lang",
  // 启动页面
  launch: "/pages/launch/index",
  // 服务页面
  services: "/pages/services/index",
  // 集卡活动页面
  activity: "/pages/activity/index",
  // 集卡活动抽奖页面
  activityLottery: "/pages/activity/lottery",
  // 集卡活动兑换记录页面
  activityExchangeRecord: "/pages/activity/exchange_record",
  // 集卡活动记录页面
  activityCardRecord: "/pages/activity/card_record",
  // 集卡规则页面
  activityRules: "/pages/activity/rules",
  // 任务市场页面
  taskIndex: "/pages/task/index",
  // 盲盒抽奖次数记录页面
  taskLotteryRecord: "/pages/task/lottery_record",
  // 盲盒奖品记录页面
  taskRecord: "/pages/task/record",
  // 任务奖励页面
  taskRewards: "/pages/task/task-rewards",
  // VIP体验券页面
  vipExperienceCoupon: "/pages/coupon/vip_experience",
  // 券包页面
  couponPackage: "/pages/profile/coupon_package",
  // 推广等级详情页面
  promotionLevelDetail: "/pages/promotion/level_detail",
};
